"""
CoarseSteering14: coarse group steering over the full (still rank-deficient)
actuation matrix — the 14-robot generalisation of ``capswitcher``'s primitive.

A single coarse control of move-group ``g`` has two physical parts:

1. **Rotation.** All robots rotate according to the actuation matrix ``A``
   (columns = complements of the *original* groups + the all-ones empty-group
   column).  ``A`` has rank ``K`` (5 for 14 robots) which is far below ``N``,
   so the reachable rotation subspace is low-dimensional — the rank-deficiency
   problem arises naturally and **no column is dropped** (unlike the 6-robot
   system's artificial rank-2 reduction).  With no random drop the whole coarse
   control is a *deterministic* function of (state, group): no seed threading,
   and ``pinv(A)`` is precomputed once.

       least-squares heading:   t* = pinv(A) @ dθ_desired
       nonlinear progress:      t* = argmax  Σ_members  Δdistance_to_goal(t)

   and apply ``dθ_actual = A @ t*`` to every robot.

2. **Move.** Only the *members* of the chosen move-group advance forward by the
   group's configured translation length ``move_distances[group]``; non-members
   hold still.

Move-groups vs actuation columns
--------------------------------
Unlike the 6-robot system, the selectable move-groups are **not** the actuation
columns: they are the 22 subgroups (sizes 3/4/7) generated by the binary group
algebra in ``group_generator.py``.  The rotation phase always uses the full
``A``; the chosen group only decides who translates (and therefore the step
cost and the achievable progress).

Frame format, sub-step splitting and the ``move_distance`` / ``lin_max``
distinction are identical to ``capswitcher.policies.coarse_steering`` — see
that module's docstring for the physical discussion.

The nonlinear rotation solve
----------------------------
``t`` has ``K = 5`` entries but the nonlinear objective scores only the
*members'* progress, and ``rank(A_m)`` is 3–4 for every move-group.  The
optimum is therefore never a point: a 1–2 dimensional **null space** of ``t``
leaves every member's rotation untouched while still turning the non-members
(the shared actuation columns rotate everybody).  Something has to break that
tie, and the choice is physically visible — bystander rotation feeds the swept
path, hence the shield's clearance verdict, and ``n_rot`` is set by the largest
turn over *all* robots.

The tie-break here is **inherit it from the least-squares start**: ``t_ls =
pinv(A) @ dθ_desired`` aims every robot at its own goal as well as the rank
allows, and the solve only ever moves ``t`` along gradient directions, which
lie in ``row(A_m)``.  The null component of ``t_ls`` therefore survives
untouched: members get the motion that maximises their progress, bystanders
keep the best-effort turn toward their own goals.

Every solver below preserves that invariant — steps are built from ``∇f =
A_mᵀ w``, which stays in ``row(A_m)``.  Adding a ``λ‖t‖²`` term to the
*objective* would not: it pulls the null component toward zero and silently
switches to a different tie-break (min-rotation).

The rotation is then wrapped into ``(−π, π]`` before it is split into frames
(see :meth:`CoarseSteering14.compute_actions`).  The objective is periodic in
each heading, so solvers routinely return a ``dθ`` carrying extra whole turns —
identical final headings, identical swept path, but an ``n_rot`` (and a frame
allocation, and a count of simulator sub-steps) proportional to the number of
spins.  Wrapping is free in every observable except that count, which it bounds
at ``ceil(π / (ang_max·step_time))``.
"""

from __future__ import annotations

import time

import numpy as np
from scipy.optimize import minimize


def _angle_wrap(angle: np.ndarray) -> np.ndarray:
    """Wrap angles into (−π, π]."""
    return (angle + np.pi) % (2.0 * np.pi) - np.pi


class CoarseSteering14:
    """
    Coarse group steering for a swarm of coupled unicycle robots.

    Args:
        A_full:        (N, K) actuation matrix; ``A[i, s] = 1`` means robot ``i``
                       rotates when actuation column ``s`` is driven.  Used whole —
                       never reduced.
        move_groups:   List of member index arrays — the selectable coarse
                       move-groups (0-based ids are positions in this list).
        move_distance: Coarse translation length (metres) per control — a scalar
                       applied to every group, or a ``{group_id: distance}``
                       mapping covering every selectable group (e.g.
                       ``SwitcherCost.move_distances``). Default 0.5.
        method:        ``"least_squares"`` (pinv heading) or ``"nonlinear"``
                       (maximise members' distance-to-goal reduction).
        nonlinear_solver: How ``method="nonlinear"`` is solved.  All three
                       optimise the same objective from the same ``t_ls``
                       start and preserve the null-space tie-break, but the
                       objective is **wildly multi-modal** (see below), so
                       which local optimum you land on is a property of the
                       solver's path, not of the objective:

                       * ``"bfgs_lean"`` (default) — hand-rolled BFGS (no
                         scipy), 2.2× faster than ``"bfgs"`` and 6.7× faster
                         than ``"bfgs_fd"`` (329 µs vs 718 / 2215 µs per
                         solve).  Its line search differs, so it lands on a
                         *different, equally good* local optimum in most
                         solves: over 6600 solves its mean objective is within
                         0.02% of the reference.
                       * ``"bfgs"`` — scipy BFGS with the analytic gradient.
                         Same iterates as ``"bfgs_fd"`` to ~1e-5 rad, 2.8×
                         faster: the finite-difference gradient cost 6
                         objective evaluations per iteration, this costs 1.
                       * ``"bfgs_fd"`` — scipy BFGS with finite differences.
                         The original implementation, kept as the reference.

                       A damped trust-region Newton solver used to live here
                       too.  It was removed on 2026-08-17: it converged to a
                       nearby *worse* stationary point (15.4% less member
                       progress over 6600 solves), and the only thing it was
                       better at — bounded rotations — is now handled for
                       every solver by the wrap in :meth:`compute_actions`.
        step_time:     Simulator step duration (s). Default 0.3.
        ang_max:       Max angular velocity magnitude (rad/s). Default 1.0.
        lin_max:       Max linear velocity (m/s). Default 0.5.
    """

    _SOLVERS = ("bfgs_lean", "bfgs", "bfgs_fd")

    def __init__(
        self,
        A_full: np.ndarray,
        move_groups: list,
        move_distance: float | dict = 0.5,
        method: str = "least_squares",
        step_time: float = 0.3,
        ang_max: float = 1.0,
        lin_max: float = 0.5,
        nonlinear_solver: str = "bfgs_lean",
        trust_rad: float = 0.5,
    ) -> None:
        if method not in ("least_squares", "nonlinear"):
            raise ValueError(
                f"method must be 'least_squares' or 'nonlinear' (got {method!r})."
            )
        if nonlinear_solver not in self._SOLVERS:
            raise ValueError(
                f"nonlinear_solver must be one of {self._SOLVERS} "
                f"(got {nonlinear_solver!r})."
            )
        self.A_full = np.asarray(A_full, dtype=np.float64)
        if self.A_full.ndim != 2:
            raise ValueError(f"A_full must be 2-D (got shape {self.A_full.shape}).")
        self.num_robots = int(self.A_full.shape[0])

        self._members = [np.asarray(g, dtype=int) for g in move_groups]
        if not self._members:
            raise ValueError("move_groups must be non-empty.")
        for g in self._members:
            if g.size == 0:
                raise ValueError("every move-group must have at least one member.")
            if g.min() < 0 or g.max() >= self.num_robots:
                raise ValueError(f"move-group {g.tolist()} out of range for N={self.num_robots}.")

        group_ids = range(len(self._members))
        if isinstance(move_distance, dict):
            missing = [g for g in group_ids if g not in move_distance]
            if missing:
                raise ValueError(f"move_distance mapping missing groups {missing}")
            self.move_distances = {g: float(move_distance[g]) for g in group_ids}
        else:
            self.move_distances = {g: float(move_distance) for g in group_ids}
        if any(d < 0.0 for d in self.move_distances.values()):
            raise ValueError("move_distance must be non-negative")
        self.method = method
        self.nonlinear_solver = nonlinear_solver
        self.trust_rad = float(trust_rad)
        self.step_time = float(step_time)
        self.ang_max = float(ang_max)
        self.lin_max = float(lin_max)

        self._pinv_A = np.linalg.pinv(self.A_full)

        # Wall-clock seconds spent in the most recent rotation solve, and the
        # iterations it took (0 for the closed-form least-squares method).
        self.last_solve_time_s: float = 0.0
        self.last_solve_iterations: int = 0

    # ------------------------------------------------------------------

    def selectable_groups(self) -> list[int]:
        """0-based ids of all selectable move-groups."""
        return list(range(len(self._members)))

    def members_of(self, group: int) -> np.ndarray:
        """Robot indices that move when move-group ``group`` (0-based) is chosen."""
        return self._members[group]

    # ------------------------------------------------------------------

    @staticmethod
    def _rotation_terms(
        t: np.ndarray,
        theta_m: np.ndarray,
        A_m: np.ndarray,
        dist0: np.ndarray,
        phi: np.ndarray,
        d: float,
    ) -> tuple[float, np.ndarray]:
        """
        Objective and gradient of the rotation solve.

        In polar form — with ``L = ‖g − p‖`` the current distance, ``φ`` the
        bearing to the goal and ``δ = θ + A_m·t − φ`` the post-rotation heading
        error — one member's distance after moving ``d`` metres forward is::

            D = √(L² − 2·d·L·cos δ + d²)

        so ``f = Σ D`` (minimised; the ``−Σ L`` that makes it a *progress* has
        zero gradient and is added by the caller only for reporting), and::

            ∂D/∂δ = d·L·sin δ / D                      ⇒  ∇f = A_mᵀ w

        The gradient is exact, so no finite differences are needed.  Note it is
        built from ``A_mᵀ``: every step made from it lies in ``row(A_m)``,
        which is what preserves the null-space tie-break.

        The analytic Hessian ``H = A_mᵀ diag((d·L·cos δ − w²) / D) A_m`` was
        computed here too; it went with the Newton solver on 2026-08-17.
        """
        delta = theta_m + A_m @ t - phi
        sin_d, cos_d = np.sin(delta), np.cos(delta)
        # D ≥ |L − d| > 0 unless a member sits exactly d metres from its goal.
        D = np.sqrt(np.maximum(dist0 * dist0 - 2.0 * d * dist0 * cos_d + d * d,
                               1e-18))
        w = d * dist0 * sin_d / D
        return float(np.sum(D)), A_m.T @ w

    def _solve_bfgs_lean(
        self,
        t_ls: np.ndarray,
        theta_m: np.ndarray,
        A_m: np.ndarray,
        dist0: np.ndarray,
        phi: np.ndarray,
        d: float,
        gtol: float = 1e-5,
        max_iter: int = 200,
    ) -> np.ndarray:
        """
        BFGS without scipy: the same algorithm as the reference, ~6.6× faster.

        Two-thirds of scipy's cost on this problem is its own scaffolding —
        for a 5-dimensional objective that evaluates in ~8 µs, the wrapper
        costs more than the mathematics.  This keeps the inverse-Hessian
        recursion and a Wolfe line search (Armijo + curvature) and drops the
        rest.  The curvature test guards the update: if ``yᵀs ≤ 0`` the
        approximation would lose positive-definiteness, so the update is
        skipped rather than corrupted.

        **The trust region is not optional.**  The objective is periodic in
        each member's heading, so "this move decreases f" does not bound how
        far the move travels: the Wolfe search *grows* ``alpha`` (doubling,
        up to 30 times per iteration) whenever the objective is still falling
        at the end of a step, and on this landscape that walks the iterate to
        a legitimately-lower but physically absurd optimum hundreds of
        thousands of radians away.  Measured before the cap: mean ``n_rot``
        125.6, worst 248699 sub-steps for a single coarse edge; the lazy tree
        holds every vetted edge's frames for the whole decision, so runs were
        OOM-killed at ~27 GB.

        Note the cap is on ``alpha · step``, the **accepted displacement** —
        capping ``step`` alone does nothing, because ``alpha`` then scales it
        straight back up.  With it: mean ``n_rot`` 12.1, worst 34, mean
        objective within 0.02% of the scipy-BFGS reference.
        """
        k = A_m.shape[1]
        eye = np.eye(k)
        t = t_ls.copy()
        f, grad = self._rotation_terms(t, theta_m, A_m, dist0, phi, d)
        H = np.eye(k)
        iters = 0
        for iters in range(1, max_iter + 1):
            if np.max(np.abs(grad)) <= gtol:
                iters -= 1
                break
            step = -H @ grad
            slope = float(grad @ step)
            if slope >= 0.0:                       # lost descent → restart
                H = np.eye(k)
                step = -grad
                slope = float(grad @ step)
            # Trust region, in radians of actual robot rotation: the largest
            # alpha whose displacement turns no robot more than `trust_rad`.
            max_rot = float(np.max(np.abs(self.A_full @ step)))
            alpha_max = (self.trust_rad / max_rot) if max_rot > 0.0 else 1.0
            alpha, lo, hi = min(1.0, alpha_max), 0.0, np.inf
            f_new, grad_new = f, grad
            for _ in range(30):
                f_new, grad_new = self._rotation_terms(
                    t + alpha * step, theta_m, A_m, dist0, phi, d
                )
                if f_new > f + 1e-4 * alpha * slope:          # Armijo
                    hi = alpha
                    alpha = 0.5 * (lo + hi)
                    continue
                if abs(float(grad_new @ step)) > 0.9 * abs(slope):   # curvature
                    if alpha >= alpha_max:       # curvature unmet, but capped
                        break
                    lo = alpha
                    alpha = (min(2.0 * alpha, alpha_max) if hi == np.inf
                             else 0.5 * (lo + hi))
                    continue
                break
            s_vec = alpha * step
            y_vec = grad_new - grad
            ys = float(y_vec @ s_vec)
            t, f, grad = t + s_vec, f_new, grad_new
            if ys > 1e-12:
                rho = 1.0 / ys
                V = eye - rho * np.outer(s_vec, y_vec)
                H = V @ H @ V.T + rho * np.outer(s_vec, s_vec)
        self.last_solve_iterations = iters
        return t

    def _solve_rotation(
        self,
        theta_current: np.ndarray,
        d_theta_desired: np.ndarray,
        px: np.ndarray,
        py: np.ndarray,
        gx: np.ndarray,
        gy: np.ndarray,
        members: np.ndarray,
        move_distance: float,
    ) -> np.ndarray:
        """
        Solve for the per-robot rotation ``dθ_actual = A @ t*`` (full matrix).

        Times the solve into ``self.last_solve_time_s``.
        """
        t0_clock = time.perf_counter()

        t_ls = self._pinv_A @ d_theta_desired  # (K,)
        self.last_solve_iterations = 0

        if self.method == "least_squares":
            t_star = t_ls
        else:
            d = move_distance
            pm = np.stack([px[members], py[members]], axis=1)        # (Nm, 2)
            gm = np.stack([gx[members], gy[members]], axis=1)        # (Nm, 2)
            theta_m = theta_current[members]                          # (Nm,)
            A_m = self.A_full[members, :]                             # (Nm, K)
            rel = gm - pm                                             # (Nm, 2)
            dist0 = np.linalg.norm(rel, axis=1)                       # (Nm,)
            phi = np.arctan2(rel[:, 1], rel[:, 0])                    # (Nm,)

            if self.nonlinear_solver == "bfgs_lean":
                t_star = self._solve_bfgs_lean(
                    t_ls, theta_m, A_m, dist0, phi, d
                )
            elif self.nonlinear_solver == "bfgs":
                def fun_and_grad(t: np.ndarray) -> tuple[float, np.ndarray]:
                    f, g = self._rotation_terms(
                        t, theta_m, A_m, dist0, phi, d
                    )
                    return f - float(np.sum(dist0)), g

                res = minimize(fun_and_grad, t_ls, jac=True, method="BFGS")
                t_star = res.x
                self.last_solve_iterations = int(res.nit)
            else:                                  # "bfgs_fd" — the reference
                def neg_progress(t: np.ndarray) -> float:
                    theta_new = theta_m + A_m @ t                     # (Nm,)
                    p_new = pm + d * np.stack(
                        [np.cos(theta_new), np.sin(theta_new)], axis=1
                    )
                    dist1 = np.linalg.norm(gm - p_new, axis=1)
                    return float(-np.sum(dist0 - dist1))              # maximise progress

                res = minimize(neg_progress, t_ls, method="BFGS")
                t_star = res.x
                self.last_solve_iterations = int(res.nit)

        d_theta_actual = self.A_full @ t_star  # (N,)
        self.last_solve_time_s = time.perf_counter() - t0_clock
        return d_theta_actual

    # ------------------------------------------------------------------

    def compute_actions(
        self, robot_state: np.ndarray, group: int
    ) -> tuple[list[list[list[float]]], list[list[float]]]:
        """
        Compute the sim-input action frames for one coarse control of ``group``.

        Deterministic given (state, group): the full actuation matrix is used, so
        there is no random column drop and no seed parameter.

        Args:
            robot_state: (N, 11) state, same column layout as the 6-robot system
                (0,1: px,py; 2,3: cosθ,sinθ; 9,10: gx,gy).
            group: 0-based move-group id (see :meth:`selectable_groups`).

        Returns:
            rotation_frames, translation_frames — same frame format as
            ``capswitcher``: lists of per-robot ``[lin, ang]`` sim-input pairs.
        """
        if group not in range(len(self._members)):
            raise ValueError(
                f"group {group} is not selectable; "
                f"choose from 0..{len(self._members) - 1}."
            )

        s = np.asarray(robot_state, dtype=np.float64)  # (N, 11)
        px, py = s[:, 0], s[:, 1]
        cos_h, sin_h = s[:, 2], s[:, 3]
        gx, gy = s[:, 9], s[:, 10]

        theta_current = np.arctan2(sin_h, cos_h)              # (N,)
        theta_desired = np.arctan2(gy - py, gx - px)          # (N,)
        d_theta_desired = _angle_wrap(theta_desired - theta_current)  # (N,)

        members = self._members[group]
        move_distance = self.move_distances[group]
        d_theta_actual = self._solve_rotation(
            theta_current, d_theta_desired, px, py, gx, gy, members, move_distance
        )
        # Execute the *short way round*.  The objective sees headings only
        # through sin/cos, so it cannot distinguish dθ from dθ + 2πk and
        # regularly returns a solution that spins robots through many full
        # turns.  Every robot ends on the same heading either way, and no robot
        # translates during the rotation phase, so the swept path and the
        # shield's verdict are unchanged — but n_rot, the frames it allocates
        # and the sub-steps the simulator executes are all bounded by
        # ceil(π / (ang_max·step_time)) instead of by whatever the solver
        # happened to return.
        d_theta_actual = _angle_wrap(d_theta_actual)

        # ---- Rotation sub-steps (split to respect ang_max) ----------------
        max_abs = float(np.max(np.abs(d_theta_actual))) if d_theta_actual.size else 0.0
        max_per_step = self.ang_max * self.step_time
        rotation_frames: list[list[list[float]]] = []
        if max_abs > 1e-9:
            n_rot = int(np.ceil(max_abs / max_per_step))
            ang_vels = d_theta_actual / (n_rot * self.step_time)
            ang_vels = np.clip(ang_vels, -self.ang_max, self.ang_max)
            frame = [[0.0, float(ang_vels[i])] for i in range(self.num_robots)]
            rotation_frames = [list(map(list, frame)) for _ in range(n_rot)]

        # ---- Translation sub-steps (split to respect lin_max) -------------
        member_set = set(int(i) for i in members)
        max_per_step_lin = self.lin_max * self.step_time
        translation_frames: list[list[list[float]]] = []
        if move_distance > 1e-9:
            n_trans = int(np.ceil(move_distance / max_per_step_lin))
            lin_cmd = move_distance / (n_trans * self.step_time)
            lin_cmd = min(lin_cmd, self.lin_max)
            frame = [
                [lin_cmd if i in member_set else 0.0, 0.0]
                for i in range(self.num_robots)
            ]
            translation_frames = [list(map(list, frame)) for _ in range(n_trans)]

        return rotation_frames, translation_frames
