"""
Group Generator for Binary Allocation-Based Subgroup Generation.

This module generates all possible robot groups based on binary allocation rules:
1. Original groups (m groups) defined by binary patterns
2. Subgroups generated through logical operations on h and g vectors

Example for 6 robots (m=3):
    Original groups (g vectors - actual group allocations):
    - g1 (group1): [0,0,0,1,1,1] -> robots {3,4,5}
    - g2 (group2): [0,1,1,0,0,1] -> robots {1,2,5}
    - g3 (group3): [1,0,1,0,1,0] -> robots {0,2,4}
    
    Complementary vectors (h vectors):
    - h1: [1,1,1,0,0,0] (complement of g1)
    - h2: [1,0,0,1,1,0] (complement of g2)
    - h3: [0,1,0,1,0,1] (complement of g3)
    
    Subgroups generated from [h_i, g_j] operations where h and g are complementary.
"""

from itertools import product
from typing import List, Set, Tuple

import numpy as np


def generate_original_groups(m: int, n: int) -> Tuple[List[np.ndarray], List[np.ndarray]]:
    """
    Generate original m groups using binary allocation.
    
    For m original groups, we generate n = 2^m - 2 robots (excluding all-0 and all-1 columns).
    Each robot is assigned a unique binary code of length m.
    
    For each group i:
    - g_i: binary vector where g_i[robot_j] = 1 if robot_j has bit i set to 1 (original group allocation)
    - h_i: complement of g_i (h_i = 1 - g_i)
    
    Args:
        m: Number of original groups (typically 3 or 4).
        n: Number of robots (must be <= 2^m - 2).
        
    Returns:
        Tuple of (h_vectors, g_vectors), each a list of m binary vectors of length n.
        
    Example:
        For m=3, n=6:
        g1 = [0,0,0,1,1,1]  (robots with bit 0 set - original group 1)
        g2 = [0,1,1,0,0,1]  (robots with bit 1 set - original group 2)
        g3 = [1,0,1,0,1,0]  (robots with bit 2 set - original group 3)
        
        h1 = [1,1,1,0,0,0]  (complement of g1)
        h2 = [1,0,0,1,1,0]  (complement of g2)
        h3 = [0,1,0,1,0,1]  (complement of g3)
    """
    max_robots = 2 ** m - 2
    if n > max_robots:
        raise ValueError(f"Number of robots {n} exceeds maximum {max_robots} for {m} groups")
    
    # Generate all binary codes excluding all-0 and all-1
    # Binary code i (1 to 2^m - 2) represents robot i-1
    robot_codes = list(range(1, n + 1))
    
    h_vectors = []
    g_vectors = []
    
    for bit_pos in range(m):
        g = np.zeros(n, dtype=int)
        for robot_idx, code in enumerate(robot_codes):
            # Check if bit at position bit_pos is set
            if (code >> bit_pos) & 1:
                g[robot_idx] = 1
        
        h = 1 - g  # Complement
        h_vectors.append(h)
        g_vectors.append(g)
    
    return h_vectors, g_vectors


def apply_logical_and(vec1: np.ndarray, vec2: np.ndarray) -> np.ndarray:
    """Apply element-wise logical AND operation."""
    return (vec1 & vec2).astype(int)


def generate_subgroups_recursive(
    h_vectors: List[np.ndarray],
    g_vectors: List[np.ndarray],
    max_depth: int = None,
    use_complement: bool = True,
) -> List[List[int]]:
    """
    Generate all possible subgroups using recursive logical operations.
    
    Subgroups are generated by:
    1. [h_i, g_j]: Logical AND of h_i and g_j where i can equal j
    2. [h_k, [h_i, g_j]]: Further recursive operations
    3. [f-h_i, g_j]: Using complement f = [1,1,...,1] where f-h_i = g_i
    
    Rules:
    - Each h_i or g_i can appear at most once in any subgroup expression
    - f can be applied to multiple different h vectors: [f-h_i, [f-h_j, ...]] is valid if i≠j
    - Maximum chain depth is m (number of original groups)
    
    Args:
        h_vectors: List of h vectors from original groups.
        g_vectors: List of g vectors from original groups.
        max_depth: Maximum recursion depth (None = unlimited, defaults to m).
        use_complement: Whether to use f-h complement operation.
        
    Returns:
        List of subgroups, where each subgroup is a list of robot indices.
    """
    m = len(h_vectors)
    n = len(h_vectors[0])
    
    if max_depth is None:
        max_depth = m
    
    # Track unique subgroups (as tuples for hashing)
    unique_subgroups = set()
    
    # Add original groups (from g vectors - these are the actual group allocations)
    for g in g_vectors:
        robot_indices = tuple(np.where(g == 1)[0].tolist())
        if robot_indices:  # Non-empty
            unique_subgroups.add(robot_indices)
    
    # Queue stores: (current_vector, depth, used_h_indices, used_g_indices, label)
    # used_h_indices and used_g_indices track which vectors have been used
    queue = []
    
    # Initial candidates: Start with each g_i
    for i in range(m):
        used_g = frozenset([i])
        queue.append((g_vectors[i].copy(), 0, frozenset(), used_g, f"g{i}"))
    
    # BFS exploration
    visited = {}  # Map from (vec_tuple, used_h, used_g) to avoid redundant computation
    
    while queue:
        vec, depth, used_h, used_g, label = queue.pop(0)
        
        # Create state key
        vec_tuple = tuple(vec)
        state_key = (vec_tuple, used_h, used_g)
        
        if state_key in visited:
            continue
        visited[state_key] = True
        
        # Check depth limit
        if depth >= max_depth:
            continue
        
        # Try combining with h_i or (f-h_i)
        for i in range(m):
            # Skip if h_i already used
            if i in used_h:
                continue
            
            # Option 1: Combine with h_i
            new_vec_h = apply_logical_and(vec, h_vectors[i])
            robot_indices_h = tuple(np.where(new_vec_h == 1)[0].tolist())
            if robot_indices_h:
                if robot_indices_h not in unique_subgroups:
                    unique_subgroups.add(robot_indices_h)
                new_used_h = used_h | frozenset([i])
                queue.append((new_vec_h, depth + 1, new_used_h, used_g, f"[h{i},{label}]"))
            
            # Option 2: Combine with (f-h_i) = g_i, but only if g_i not already used
            if use_complement and i not in used_g:
                new_vec_g = apply_logical_and(vec, g_vectors[i])
                robot_indices_g = tuple(np.where(new_vec_g == 1)[0].tolist())
                if robot_indices_g:
                    if robot_indices_g not in unique_subgroups:
                        unique_subgroups.add(robot_indices_g)
                    new_used_h = used_h | frozenset([i])
                    new_used_g = used_g | frozenset([i])
                    queue.append((new_vec_g, depth + 1, new_used_h, new_used_g, f"[(f-h{i}),{label}]"))
    
    # Convert to list of lists
    subgroups = [list(indices) for indices in unique_subgroups]
    
    # Sort by size then by robot indices for consistency
    subgroups.sort(key=lambda g: (len(g), g))
    
    return subgroups


def generate_all_groups(
    m: int,
    n: int = None,
    max_depth: int = None,
    use_complement: bool = True,
    include_singletons: bool = True,
) -> List[List[int]]:
    """
    Generate all possible robot groups given original group number m and robot count n.
    
    This is the main entry point for group generation.
    
    Args:
        m: Number of original groups (typically 3 or 4).
            - m=3: supports up to 6 robots (2^3 - 2)
            - m=4: supports up to 14 robots (2^4 - 2)
        n: Number of robots. If None, uses maximum (2^m - 2).
        max_depth: Maximum recursion depth for subgroup generation (None = unlimited).
        use_complement: Whether to use f-h complement operation.
        include_singletons: Whether to include single-robot groups.
        
    Returns:
        List of all possible groups, where each group is a list of robot indices.
        
    Example:
        >>> groups = generate_all_groups(m=3, n=6)
        >>> print(f"Generated {len(groups)} groups for 6 robots")
        >>> print(f"Size-1: {sum(1 for g in groups if len(g) == 1)}")
        >>> print(f"Size-2: {sum(1 for g in groups if len(g) == 2)}")
        >>> print(f"Size-3: {sum(1 for g in groups if len(g) == 3)}")
    """
    # Use maximum robots if n is not specified
    if n is None:
        n = 2 ** m - 2
    
    # Validate inputs
    max_robots = 2 ** m - 2
    if n > max_robots:
        raise ValueError(
            f"Number of robots {n} exceeds maximum {max_robots} for {m} groups. "
            f"Use m={int(np.ceil(np.log2(n + 2)))} for {n} robots."
        )
    
    # Generate original groups
    h_vectors, g_vectors = generate_original_groups(m, n)
    
    # Generate all subgroups
    subgroups = generate_subgroups_recursive(
        h_vectors=h_vectors,
        g_vectors=g_vectors,
        max_depth=max_depth,
        use_complement=use_complement,
    )
    
    # Filter out singletons if requested
    if not include_singletons:
        subgroups = [g for g in subgroups if len(g) > 1]
    
    return subgroups


def filter_groups_by_size(
    groups: List[List[int]],
    min_size: int = 1,
    max_size: int = 3,
) -> List[List[int]]:
    """
    Filter groups by size constraints.
    
    Args:
        groups: List of groups to filter.
        min_size: Minimum group size (inclusive).
        max_size: Maximum group size (inclusive).
        
    Returns:
        Filtered list of groups with size in [min_size, max_size].
        
    Example:
        >>> all_groups = generate_all_groups(m=3, n=6)
        >>> small_groups = filter_groups_by_size(all_groups, min_size=1, max_size=3)
        >>> print(f"Groups with size <= 3: {len(small_groups)}")
    """
    filtered = [g for g in groups if min_size <= len(g) <= max_size]
    return filtered


def print_group_statistics(groups: List[List[int]], n: int, max_display_per_size: int = None):
    """
    Print statistics about generated groups.
    
    Args:
        groups: List of groups.
        n: Total number of robots.
        max_display_per_size: Maximum number of groups to display per size (None = show all).
    """
    print(f"\n{'='*60}")
    print(f"Group Generation Statistics ({n} robots)")
    print(f"{'='*60}")
    print(f"Total groups: {len(groups)}")
    
    # Size distribution
    size_counts = {}
    for group in groups:
        size = len(group)
        size_counts[size] = size_counts.get(size, 0) + 1
    
    print("\nSize distribution:")
    for size in sorted(size_counts.keys()):
        count = size_counts[size]
        pct = count / len(groups) * 100
        print(f"  Size-{size}: {count:4d} groups ({pct:5.1f}%)")
    
    # Show all groups by size (or limited by max_display_per_size)
    print("\nAll groups by size:")
    for size in sorted(size_counts.keys()):
        groups_of_size = [g for g in groups if len(g) == size]
        if max_display_per_size is not None and len(groups_of_size) > max_display_per_size:
            print(f"  Size-{size} (showing first {max_display_per_size} of {len(groups_of_size)}):")
            for g in groups_of_size[:max_display_per_size]:
                print(f"    {g}")
            print(f"    ... ({len(groups_of_size) - max_display_per_size} more)")
        else:
            print(f"  Size-{size} (all {len(groups_of_size)}):")
            for g in groups_of_size:
                print(f"    {g}")
    
    print(f"{'='*60}\n")


# Example usage and testing
if __name__ == "__main__":
    
    # Test case 5: Filter groups by size (max size 3)
    print("\n" + "="*60)
    print("Test Case 5: 6 robots, filtered to size <= 3")
    print("="*60)
    
    all_groups = generate_all_groups(m=3, n=6, use_complement=True)
    filtered_groups = filter_groups_by_size(all_groups, min_size=1, max_size=3)
    print(f"Before filtering: {len(all_groups)} groups")
    print(f"After filtering (size <= 3): {len(filtered_groups)} groups")
    print_group_statistics(filtered_groups, n=6)
    
    # Test case 6: 14 robots, filtered to size <= 3
    print("\n" + "="*60)
    print("Test Case 6: 14 robots, filtered to size <= 3")
    print("="*60)
    
    all_groups_14 = generate_all_groups(m=4, n=14, use_complement=True)
    filtered_groups_14 = filter_groups_by_size(all_groups_14, min_size=1, max_size=7)
    print(f"Before filtering: {len(all_groups_14)} groups")
    print(f"After filtering (size <= 3): {len(filtered_groups_14)} groups")
    print_group_statistics(filtered_groups_14, n=14, max_display_per_size=22)