"""
CAPSwitcher-14: the 14-robot instantiation of the coarse/precise switcher.

Sibling package of ``capswitcher`` (the 6-robot system, left untouched).  This
package holds everything whose semantics changed for the scaled system:

* 22 coarse move-groups (sizes 3/4/7) generated by the binary group algebra
  (``policies/group_generator.py``), full-rank-5 actuation with **no** artificial
  column drop (``policies/coarse_steering.py``, deterministic — no drop RNG);
* a forward model with **single-edge** transitions (``rl/forward_model.py``) so
  a tree search pays per materialised edge, not per fully-expanded node;
* the lazy Gumbel AlphaZero search (``rl/search/``): cheap learned prior ranks
  all edges, transitions are bought one at a time, shield-refuted coarse edges
  are pruned from the legal set, unvisited edges use completed-Q (v_mix).

N-generic leaf utilities (shield geometry sweep, reward, GAT backbone) are
imported from ``capswitcher`` rather than forked.

Intentionally import-light: submodules are imported explicitly by consumers so
that sim-free work (tests, training scripts) does not pull in torch/irsim.
"""
